<?php

namespace common\models\activity\sections;

use common\models\activity\fields\blocks\ActivityEffectivenessOfTheActionBlock;
use common\models\activity\fields\blocks\BaseBlockModel;

/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 03.09.2018
 * Time: 11:48
 */

class ActivitySectionEffectivenessOfTheAction extends BaseBlockModel {
    /*protected $_block_template = 'partials/blocks/_effectiveness_of_the_action';
    protected $_block_fields_templates = 'partials/blocks/_effectiveness_of_the_action_fields_list.php';*/

    public function beforeSave($insert)
    {
        $this->header = is_null($this->header) ? 'Результативность акции' : $this->header;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getModel() {
        return new ActivityEffectivenessOfTheActionBlock();
    }
}
