<?php

namespace common\models\activity\sections;

use common\models\activity\ActivityExtendedStatisticSections;

/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 03.09.2018
 * Time: 11:48
 */

class ActivitySectionEffectivenessOfTheAction extends ActivityExtendedStatisticSections {
    protected $_block_template = 'partials/blocks/_effectiveness_of_the_action';

    public function beforeSave($insert)
    {
        $this->header = is_null($this->header) ? 'Результативность акции' : $this->header;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
