<?php

namespace common\models\activity\sections;

use common\models\activity\ActivityExtendedStatisticSections;
use common\models\activity\fields\blocks\ActivityTargetBlock;

/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 03.09.2018
 * Time: 11:48
 *
 * @property mixed $model
 */

class ActivitySectionTargets extends ActivityExtendedStatisticSections {
    protected $_block_template = 'partials/blocks/_targets';

    public function beforeSave($insert)
    {
        $this->header = is_null($this->header) ? 'Цели' : $this->header;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getModel() {
        return new ActivityTargetBlock();
    }

    public function render($view)
    {
        $html = parent::render($view); // TODO: Change the autogenerated stub
        $html .= $view->renderPartial($this->_block_template, [ 'section' => $this, 'model' => $this->getModel() ]);

        return $html;
    }
}
