<?php

namespace common\models\activity\sections;

use common\models\activity\ActivityExtendedStatisticSections;

/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 03.09.2018
 * Time: 11:48
 */

class ActivitySectionClients extends ActivityExtendedStatisticSections {

    protected $_block_template = 'partials/blocks/_clients';

    public function beforeSave($insert)
    {
        $this->header = is_null($this->header) ? 'Клиенты' : $this->header;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
