<?php
/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 20.11.2017
 * Time: 12:58
 */

namespace backend\controllers;


use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class ActivityServiceController extends PageController
{
    const PAGE_URL = '/activity-service';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function init()
    {
        $this->_page_icon = '';
        $this->_page_header = 'Параметры статистики (SC)';
        $this->_page_description = 'Настройка паметров заполнения статистики';

        $this->_current_page = self::PAGE_URL;

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $this->makeBreadCrumb([
            '' => \Yii::t('app', $this->_page_header)
        ]);

        return $this->render('index');
    }
}
