<?php
/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 16.11.2017
 * Time: 13:03
 */

namespace backend\controllers;

use common\models\activity\Activity;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

class PageController extends Controller
{
    protected $_page_icon = 'line_style';
    protected $_page_header = 'Главная';
    protected $_page_description = 'Основная информация';
    protected $_breadcrumb = [];
    protected $_current_page = '/admin';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function render($view, $params = [])
    {
        $this->setCurrentPage();

        $this->pageInfo();
        $this->makeBreadCrumb([]);

        $params['meta_title'] = $this->_page_header;
        $this->view->title = $this->_page_header;

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    protected function makeBreadCrumb($breadcrums = []) {
        \Yii::$app->session->set('breadcrumb', null);

        $this->_breadcrumb[Url::to('/admin')] = Yii::t('app', 'Главная');

        foreach ($breadcrums as $url => $label) {
            $this->_breadcrumb[$url] = $label;
        }

        \Yii::$app->session->set('breadcrumb', $this->_breadcrumb);
    }

    protected function pageInfo() {
        \Yii::$app->session->set('page_icon', $this->_page_icon);
        \Yii::$app->session->set('page_header', $this->_page_header);
        \Yii::$app->session->set('page_description', $this->_page_description);
    }

    protected function setCurrentPage() {
        \Yii::$app->session->set('current_page', $this->_current_page);
    }

    /**
     * @return array|null|\yii\db\ActiveRecord|\yii\web\Response
     */
    protected function getActivity() {
        $activity_id = Yii::$app->request->get('id') ?  Yii::$app->request->get('id') : Yii::$app->request->post('id');
        $activity = Activity::find()->where(['id' => $activity_id])->one();

        if (!$activity) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Активность не найдена.'));

            return $this->redirect(Url::to(['admin']));
        }

        return $activity;
    }
}
