<?php

namespace common\models\activity\statistic;

use common\models\activity\ActivityExtendedStatisticSections;

class ActivitySettingsBlock extends ActivityExtendedStatisticSections
{
    /**
     * @inheritdoc
     */
    public function rules ()
    {
        return [
            [['description'], 'required'],
            [['description', 'graph_type'], 'string'],
            [['status', 'allow_use_fields_in_others_blocks'], 'integer'],
        ];
    }

    public function load($data, $formName = null)
    {
        //Тупая проверка на установленный чекбокс, поже убрать
        $check_fields = ['status', 'allow_use_fields_in_others_blocks'];
        foreach ($check_fields as $field) {
            if (!isset($data[self::formName()][$field])) {
                $data[self::formName()][$field] = 0;
            }
        }

        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }
}
