<?php

namespace common\models\activity\steps;

use Yii;

/**
 * This is the model class for table "activity_extended_statistic_steps".
 *
 * @property integer $id
 * @property integer $action_after
 * @property integer $activity_id
 * @property string $header
 * @property string $description
 * @property string $step_type
 */
class ActivityExtendedStatisticSteps extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activity_extended_statistic_steps';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['action_after', 'activity_id'], 'integer'],
            [['activity_id', 'header'], 'required'],
            [['step_type'], 'string'],
            [['header', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'action_after' => 'Значение',
            'activity_id' => 'ActivityController ID',
            'header' => 'Название',
            'description' => 'Описание',
            'step_type' => 'Тип шага',
        ];
    }

    public static function getStepsTypes() {
        return self::getStepTypesList();
    }

    public function beforeDelete ()
    {
        ActivityExtendedStatisticStepValues::deleteAll(['step_id' => $this->id]);
        
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public static function getStepTypeLabel($type) {
        $result = array_filter(self::getStepsTypes(), function($item) use($type) {
            return $item['id'] == $type ? $item : null;
        });

        $result = array_pop($result);
        if (!empty($result)) {
            return $result['name'];
        }

        return '';
    }

    public static function getStepTypesList() {
        return [ [ 'id' => 'none', 'name' => 'Нет' ],
            [ 'id' => 'mail_action_end', 'name' => 'Окончание мероприятия' ],
            [ 'id' => 'mail_certificate_end', 'name' => 'Срок действия сертификата' ]
        ];
    }
}
